export const products = [
  // Electronics
  {
    id: 1,
    name: "Wireless Headphones",
    price: 79.99,
    category: "Electronics",
    rating: 4.5,
    stock: 15,
    image: "Wireless Headphones",
  },
  {
    id: 2,
    name: "USB-C Cable",
    price: 12.99,
    category: "Electronics",
    rating: 4.7,
    stock: 50,
    image: "USB-C Cable",
  },
  {
    id: 3,
    name: "Portable Charger",
    price: 34.99,
    category: "Electronics",
    rating: 4.6,
    stock: 25,
    image: "Portable Charger",
  },
  {
    id: 4,
    name: "Phone Stand",
    price: 15.99,
    category: "Electronics",
    rating: 4.4,
    stock: 30,
    image: "Phone Stand",
  },
  {
    id: 5,
    name: "Mechanical Keyboard",
    price: 89.99,
    category: "Electronics",
    rating: 4.8,
    stock: 12,
    image: "Mechanical Keyboard",
  },
  {
    id: 6,
    name: "Wireless Mouse",
    price: 29.99,
    category: "Electronics",
    rating: 4.5,
    stock: 20,
    image: "Wireless Mouse",
  },
  {
    id: 7,
    name: "Webcam 1080p",
    price: 59.99,
    category: "Electronics",
    rating: 4.3,
    stock: 18,
    image: "Webcam 1080p",
  },
  {
    id: 8,
    name: "Laptop Stand",
    price: 39.99,
    category: "Electronics",
    rating: 4.6,
    stock: 22,
    image: "Laptop Stand",
  },
  {
    id: 9,
    name: "SSD 256GB",
    price: 49.99,
    category: "Electronics",
    rating: 4.7,
    stock: 14,
    image: "SSD 256GB",
  },
  {
    id: 10,
    name: "HDMI Cable",
    price: 9.99,
    category: "Electronics",
    rating: 4.4,
    stock: 60,
    image: "HDMI Cable",
  },

  // Fashion
  {
    id: 11,
    name: "Cotton T-Shirt",
    price: 19.99,
    category: "Fashion",
    rating: 4.5,
    stock: 35,
    image: "Cotton T-Shirt",
  },
  {
    id: 12,
    name: "Denim Jeans",
    price: 59.99,
    category: "Fashion",
    rating: 4.6,
    stock: 25,
    image: "Denim Jeans",
  },
  {
    id: 13,
    name: "Casual Sneakers",
    price: 74.99,
    category: "Fashion",
    rating: 4.7,
    stock: 18,
    image: "Casual Sneakers",
  },
  {
    id: 14,
    name: "Baseball Cap",
    price: 24.99,
    category: "Fashion",
    rating: 4.3,
    stock: 40,
    image: "Baseball Cap",
  },
  {
    id: 15,
    name: "Winter Jacket",
    price: 129.99,
    category: "Fashion",
    rating: 4.8,
    stock: 12,
    image: "Winter Jacket",
  },
  {
    id: 16,
    name: "Wool Socks Pack",
    price: 14.99,
    category: "Fashion",
    rating: 4.4,
    stock: 45,
    image: "Wool Socks Pack",
  },
  {
    id: 17,
    name: "Leather Belt",
    price: 44.99,
    category: "Fashion",
    rating: 4.5,
    stock: 20,
    image: "Leather Belt",
  },
  {
    id: 18,
    name: "Beanie Hat",
    price: 22.99,
    category: "Fashion",
    rating: 4.6,
    stock: 30,
    image: "Beanie Hat",
  },

  // Home & Garden
  {
    id: 19,
    name: "Table Lamp",
    price: 39.99,
    category: "Home & Garden",
    rating: 4.5,
    stock: 16,
    image: "Table Lamp",
  },
  {
    id: 20,
    name: "Throw Pillow",
    price: 29.99,
    category: "Home & Garden",
    rating: 4.7,
    stock: 28,
    image: "Throw Pillow",
  },
  {
    id: 21,
    name: "Area Rug",
    price: 89.99,
    category: "Home & Garden",
    rating: 4.6,
    stock: 10,
    image: "Area Rug",
  },
  {
    id: 22,
    name: "Plant Pot",
    price: 19.99,
    category: "Home & Garden",
    rating: 4.4,
    stock: 32,
    image: "Plant Pot",
  },
  {
    id: 23,
    name: "Shower Curtain",
    price: 34.99,
    category: "Home & Garden",
    rating: 4.5,
    stock: 22,
    image: "Shower Curtain",
  },
  {
    id: 24,
    name: "Bath Towel Set",
    price: 44.99,
    category: "Home & Garden",
    rating: 4.8,
    stock: 18,
    image: "Bath Towel Set",
  },
  {
    id: 25,
    name: "Wall Clock",
    price: 24.99,
    category: "Home & Garden",
    rating: 4.6,
    stock: 25,
    image: "Wall Clock",
  },
  {
    id: 26,
    name: "Bedsheet Set",
    price: 54.99,
    category: "Home & Garden",
    rating: 4.7,
    stock: 15,
    image: "Bedsheet Set",
  },

  // Sports & Outdoors
  {
    id: 27,
    name: "Yoga Mat",
    price: 29.99,
    category: "Sports",
    rating: 4.5,
    stock: 20,
    image: "Yoga Mat",
  },
  {
    id: 28,
    name: "Water Bottle",
    price: 19.99,
    category: "Sports",
    rating: 4.6,
    stock: 35,
    image: "Water Bottle",
  },
  {
    id: 29,
    name: "Dumbbells Set",
    price: 79.99,
    category: "Sports",
    rating: 4.7,
    stock: 12,
    image: "Dumbbells Set",
  },
  {
    id: 30,
    name: "Resistance Bands",
    price: 24.99,
    category: "Sports",
    rating: 4.4,
    stock: 28,
    image: "Resistance Bands",
  },
  {
    id: 31,
    name: "Running Shoes",
    price: 99.99,
    category: "Sports",
    rating: 4.8,
    stock: 14,
    image: "Running Shoes",
  },
  {
    id: 32,
    name: "Jump Rope",
    price: 14.99,
    category: "Sports",
    rating: 4.5,
    stock: 40,
    image: "Jump Rope",
  },
  {
    id: 33,
    name: "Sports Backpack",
    price: 44.99,
    category: "Sports",
    rating: 4.6,
    stock: 19,
    image: "Sports Backpack",
  },

  // Books
  {
    id: 34,
    name: "Fiction Novel",
    price: 14.99,
    category: "Books",
    rating: 4.7,
    stock: 50,
    image: "Fiction Novel",
  },
  {
    id: 35,
    name: "Programming Book",
    price: 34.99,
    category: "Books",
    rating: 4.8,
    stock: 18,
    image: "Programming Book",
  },
  {
    id: 36,
    name: "Biography",
    price: 19.99,
    category: "Books",
    rating: 4.5,
    stock: 25,
    image: "Biography",
  },
  {
    id: 37,
    name: "Self-Help Guide",
    price: 17.99,
    category: "Books",
    rating: 4.6,
    stock: 30,
    image: "Self-Help Guide",
  },
  {
    id: 38,
    name: "Cookbook",
    price: 24.99,
    category: "Books",
    rating: 4.4,
    stock: 22,
    image: "Cookbook",
  },
  {
    id: 39,
    name: "Children Story",
    price: 12.99,
    category: "Books",
    rating: 4.7,
    stock: 40,
    image: "Children Story",
  },

  // Beauty & Personal Care
  {
    id: 40,
    name: "Face Wash",
    price: 12.99,
    category: "Beauty",
    rating: 4.5,
    stock: 45,
    image: "Face Wash",
  },
  {
    id: 41,
    name: "Moisturizer Cream",
    price: 24.99,
    category: "Beauty",
    rating: 4.6,
    stock: 28,
    image: "Moisturizer Cream",
  },
  {
    id: 42,
    name: "Shampoo Bottle",
    price: 14.99,
    category: "Beauty",
    rating: 4.7,
    stock: 35,
    image: "Shampoo Bottle",
  },
  {
    id: 43,
    name: "Lipstick Set",
    price: 32.99,
    category: "Beauty",
    rating: 4.5,
    stock: 20,
    image: "Lipstick Set",
  },
  {
    id: 44,
    name: "Hair Brush",
    price: 9.99,
    category: "Beauty",
    rating: 4.4,
    stock: 50,
    image: "Hair Brush",
  },
  {
    id: 45,
    name: "Sunscreen SPF50",
    price: 19.99,
    category: "Beauty",
    rating: 4.8,
    stock: 32,
    image: "Sunscreen SPF50",
  },

  // Kitchen & Dining
  {
    id: 46,
    name: "Coffee Maker",
    price: 69.99,
    category: "Kitchen",
    rating: 4.6,
    stock: 11,
    image: "Coffee Maker",
  },
  {
    id: 47,
    name: "Blender",
    price: 89.99,
    category: "Kitchen",
    rating: 4.7,
    stock: 8,
    image: "Blender",
  },
  {
    id: 48,
    name: "Cutting Board Set",
    price: 22.99,
    category: "Kitchen",
    rating: 4.5,
    stock: 24,
    image: "Cutting Board Set",
  },
  {
    id: 49,
    name: "Mug Set",
    price: 16.99,
    category: "Kitchen",
    rating: 4.4,
    stock: 38,
    image: "Mug Set",
  },
  {
    id: 50,
    name: "Utensil Set",
    price: 19.99,
    category: "Kitchen",
    rating: 4.6,
    stock: 28,
    image: "Utensil Set",
  },
];
